### PR TITLE
Enable inline custom view

### PR DESCRIPTION
**Pull request by vsmenon**
@alan-knight

### CODE REVIEW

**Review by alan-knight — COMMENTED** [review]
This is a much smaller change, so it's probably easier to carry forward, but it overlays the whole expandable custom format inline in the sources, which makes the UI seem a bit weird to me. But maybe it's desirable.

**Comment by vsmenon** [comment]
Do you have a different version of this?  If not, perhaps we should land - unless you think it's a regression on nothing.

**Comment by vsmenon** [comment]
ping

**Comment by alan-knight** [comment]
Playing with both, I rather like the ability to expand the inline view with this one, and it's a simpler patch. So landing this one (mine is in https://chromium-review.googlesource.com/c/chromium/src/+/775322 )

**Pull request merged**
